version: "3.9"

services:
  app:
    build:
      context:  ./backend_sql
    container_name: backend_sql
    volumes:
      - ./backend_sql:/app
    ports:
      - "8000:8000"
    networks:
      - dbnet
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    volumes:
      - ./backend_sql/postgres-data:/var/lib/postgresql/data
    networks:
      - dbnet
    restart: always

  phppgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8085:80"
    depends_on:
      - db
    restart: always
    networks:
      - dbnet



networks:
  dbnet: